"""Set up income/expense columns

Revision ID: a6a899263c9b
Revises: 86bd16a71cf7
Create Date: 2023-05-21 17:39:17.979366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a899263c9b'
down_revision = '86bd16a71cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_monthly_expenses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('average_monthly_expenses')

    # ### end Alembic commands ###
