"""Created Income Table

Revision ID: e4221b2138f8
Revises: a6a899263c9b
Create Date: 2023-05-21 18:15:16.058973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4221b2138f8'
down_revision = 'a6a899263c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week1', sa.Integer(), nullable=True),
    sa.Column('week2', sa.Integer(), nullable=True),
    sa.Column('week3', sa.Integer(), nullable=True),
    sa.Column('week4', sa.Integer(), nullable=True),
    sa.Column('total_balance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incomes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incomes')
    # ### end Alembic commands ###
